# Site settings
title: Theresa's House of Beauty and Medi Spa
email: youremailaddress@gmail.com
description: "PHONE: (08) 9591 3938, MOBILE: 0417 941 189 \\ SORRY - LADIES ONLY"
baseurl: "/dimension-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 25 Epsilon Drive
city: Rockingham
state: WA
zip_code: 6168
country: Australia
phone: +614 1794 1189

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
style: compressed
